### ISSUE TITLE
Music keeps playing when headphone is disconnected

### ISSUE THREAD

**Issue by vkareh** [Micahnator/Panpipe#5]
Default behavior in other systems (including music-app in Ubuntu Touch) is to pause playback whenever a headphone is connected or disconnected (I suspect this is also true for audio through Bluetooth, but I have not tested it). Can this behavior be added to panpipe?

**Comment by Micahnator** [comment]
Yeah, that would be a good behavior to implement, I hadn't thought about it. I will have to do some looking into the developer documentation to see if the system provides applications with the headphone jack connection state. Because the music-app is a core app it sometimes is given special permissions, but I'll look into it!

**Comment by Micahnator** [comment]
Hmm, I just tried disconnecting my headphones while Panpipe was playing music and the audio paused. Seems like the system does it automatically without my app doing anything special. I'm running Ubuntu on a N4 on the devel channel.
